package com.qualcomm.robotcore.hardware;

public enum DeviceType
{
    FTDI_USB_UNKNOWN_DEVICE, 
    MODERN_ROBOTICS_USB_DC_MOTOR_CONTROLLER, 
    MODERN_ROBOTICS_USB_DEVICE_INTERFACE_MODULE, 
    MODERN_ROBOTICS_USB_LEGACY_MODULE, 
    MODERN_ROBOTICS_USB_SENSOR_MUX, 
    MODERN_ROBOTICS_USB_SERVO_CONTROLLER, 
    MODERN_ROBOTICS_USB_UNKNOWN_DEVICE;
}
