package com.qualcomm.robotcore.hardware.configuration;

public enum ConfigurationType
{
    ACCELEROMETER, 
    ADAFRUIT_COLOR_SENSOR, 
    ANALOG_INPUT, 
    ANALOG_OUTPUT, 
    COLOR_SENSOR, 
    COMPASS, 
    DEVICE_INTERFACE_MODULE, 
    DIGITAL_DEVICE, 
    GYRO, 
    I2C_DEVICE, 
    IR_SEEKER, 
    IR_SEEKER_V3, 
    LED, 
    LEGACY_MODULE_CONTROLLER, 
    LIGHT_SENSOR, 
    MATRIX_CONTROLLER, 
    MOTOR, 
    MOTOR_CONTROLLER, 
    NOTHING, 
    OPTICAL_DISTANCE_SENSOR, 
    OTHER, 
    PULSE_WIDTH_DEVICE, 
    SERVO, 
    SERVO_CONTROLLER, 
    TOUCH_SENSOR, 
    TOUCH_SENSOR_MULTIPLEXER, 
    ULTRASONIC_SENSOR;
}
